install.packages(c(
  "plyr",
  "dplyr",
  "ggplot2",
  "formattable",
  "multcomp",
  "multcompView",
  "rstatix",
  "emmeans",
  "broom",
  "Hmisc",
  "ggpubr", 
  "vegan",
  "limma",
  "rstatix",
  "emmeans"
))
install.packages("remotes")
remotes::install_github("pmartinezarbizu/pairwiseAdonis/pairwiseAdonis")
remotes::install_github("mikemc/speedyseq")
